### ISSUE TITLE
Does Not Work When Reloading A Group of Tabs

### ISSUE THREAD

**Issue by BrandonR541** [igorlogius/load-tabs-sequentially#1]
Love this addons concept! Great Idea.

It works fine when opening links into newly created tabs, but I often have several group of tabs many (as in a parent tab and all of its children, not the actual tab group thing) that I will unload and then come back to at a later point. I will then select all of the tabs and reload them (or use the TST reload this tree function), and they will all try to load at the same time.

If you could find a way to make it work in these situations, that would be fantastic. Thanks for the work you've put into making useful stuff!

**Comment by igorlogius** [comment]
I made some modifications and i think version 1.2.4  should now be able to hanlde this usecase now too.
I am actually pretty pleased ... since i was able to remove more code than i added, which is always a plus from a maintainace perspective. 

@BrandonR541  If you like you can try it out when it's been out on AMO in a couple of hours.

**Comment by igorlogius** [comment]
Nope, ... seems i made a mistake ... and wont be releasing version 1.2.4 ...  sorry.

**Comment by BrandonR541** [comment]
Thanks for looking into it, and thank you for the suggestion, that other extension suits my needs well. I'll keep an eye out for future updates from yours as well, good luck and thanks again!
